### ISSUE TITLE
Test with newer versions of Clang and GCC

### ISSUE THREAD

**Issue by emil-e** [emil-e/rapidcheck#20]
Currently only tested with GCC-4.9 and Clang 3.4/3.6.

**Comment by whoshuu** [comment]
The build fails with gcc 5.1, see the travis output [here](https://travis-ci.org/whoshuu/rapidcheck/jobs/75541195#L261). A fair warning though, it's a bit dense, so it'll take a while to wade through

**Comment by emil-e** [comment]
Will take a look ASAP.

**Comment by emil-e** [comment]
Waiting for Travis to complete but this should fix things. The issue was simple to fix.

However, something that is more worrying is that I got an Internal Compiler Error when compiling some tests with GCC 5.2. I had to comment those two out to get it to compile. However, as a user of the library you should be fine.

In general, I strongly recommend Clang since I've had way fewer bugs with it and the build times are significantly better.

**Comment by emil-e** [comment]
That was a lie... still doesn't work with 5.1...

**Comment by emil-e** [comment]
5.1 may be a bit too broken for me to look any further since the issues seem to be fixed in 5.2.

Specifically, I get these nonsense errors when compiling the preprocessed output of one test file:

```
Fixed.pp.cpp:90723:353: error: redeclaration of ‘const long unsigned int count’
                 do { if (!(containerSize(shrink.value()) == count)) { throw ::rc::detail::CaseResult( ::rc::detail::CaseResult::Type::Failure, ::rc::detail::makeExpressionMessage("../test/gen/ContainerTests/Fixed.cpp", 24, "RC_ASSERT" "(" "containerSize(shrink.value()) == count" ")", ((::rc::detail::ExpressionCaptor()->*containerSize(shrink.value()) == count).str()))); } } while (false);
                                                                                                                                                                                                                                                                                                                                                                 ^
Fixed.pp.cpp:90723:58: note: ‘const long unsigned int count’ previously declared here
                 do { if (!(containerSize(shrink.value()) == count)) { throw ::rc::detail::CaseResult( ::rc::detail::CaseResult::Type::Failure, ::rc::detail::makeExpressionMessage("../test/gen/ContainerTests/Fixed.cpp", 24, "RC_ASSERT" "(" "containerSize(shrink.value()) == count" ")", ((::rc::detail::ExpressionCaptor()->*containerSize(shrink.value()) == count).str()))); } } while (false);
                                                          ^
```

Of course, `count` is already defined but there is no definition in the code that it complains about. There's a limit to how much I'm willing to cater to broken compilers :)

GCC 5.2 still gets an ICE on certain code but I'm going to report that and try to work around it.

**Comment by emil-e** [comment]
GCC bug report on the ICE: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67244

**Comment by emil-e** [comment]
Haven't found a simple way to install GCC 5.2 on the Ubuntu 12.04 LTS that is running on Travis so I'm putting this on hold right now. However, with the upcoming fix, GCC 5.2 should work except for some tests not building. That is mostly interesting if you're developing, though.

**Comment by emil-e** [comment]
The seems to have been fixed for GCC 5.3 so that's the target for full GCC 5 compatibility but until then, GCC 5.2 should work unless you need to build the tests.
